sudo: required
dist: trusty
language: erlang
before_install:
  - wget https://github.com/Z3Prover/z3/releases/download/z3-4.5.0/z3-4.5.0-x64-ubuntu-14.04.zip
  - unzip z3-4.5.0-x64-ubuntu-14.04.zip
  - export PATH=$PWD/z3-4.5.0-x64-ubuntu-14.04/bin:$PATH
  - export PYTHONPATH=$PWD/z3-4.5.0-x64-ubuntu-14.04/bin/python:$PYTHONPATH
  - export C_INCLUDE_PATH=$PWD/z3-4.5.0-x64-ubuntu-14.04/include/:$C_INCLUDE_PATH
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/z3-4.5.0-x64-ubuntu-14.04/bin
  - pip install protobuf==3.1.0
  - pip install parsimonious==0.7.0
script:
  - git submodule update
  - git submodule foreach make
  - export ERL_LIBS=$PWD/lib/proper:$ERL_LIBS
  - ./fetch_protoc.sh
  - autoconf
  - ./configure --with-protoc=$PWD/lib/protoc-3.1.0/bin/protoc
  - make depend
  - make all
otp_release:
  - 19.0
  - 18.3
  - 18.1	# 18.0 has a problem in dialyzer

cache:
  directories:
  - .plt
