os: linux
dist: bionic
language: erlang
before_install:
  - wget https://github.com/Z3Prover/z3/releases/download/z3-4.8.8/z3-4.8.8-x64-ubuntu-16.04.zip
  - unzip z3-4.8.8-x64-ubuntu-16.04.zip
  - mv z3-4.8.8-x64-ubuntu-16.04 z3
  - export PATH=$PWD/z3/bin:$PATH
  - export PYTHONPATH=$PWD/z3/bin/python:$PYTHONPATH
  - export C_INCLUDE_PATH=$PWD/z3/include/:$C_INCLUDE_PATH
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/z3/bin
  - sudo apt-get install python3-pip
  - sudo apt-get install python3-setuptools
  - python3 -m pip install -r requirements.txt
script:
  - git submodule update
  - git submodule foreach make
  - export ERL_LIBS=$PWD/lib/proper:$ERL_LIBS
  - ./fetch_protoc.sh
  - autoconf
  - ./configure --with-protoc=$PWD/lib/protoc-3.11.3/bin/protoc
  - make depend
  - make all
otp_release:
  - 22.3
  - 22.0
  - 21.2        # 21.3 is not available for bionic (18.04)
  - 20.3.8

cache:
  directories:
  - .plt
